[build]
  command = """
    git clone https://github.com/flutter/flutter.git -b stable --depth 1 /opt/buildhome/flutter
    export PATH="$PATH:/opt/buildhome/flutter/bin"
    flutter config --enable-web
    flutter pub get
    flutter build web --debug --no-wasm-dry-run
  """
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
